# -*- coding: utf-8 -*-
"""Untitled219.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18UG6dyIN7V-seSeyGiE6a97YZKbTODaQ
"""

import requests

url = 'http://localhost:5000/predict_api'
r = requests.post(url,json={'income':2, 'age':9, 'loan':6, 'LTI':7})

print(r.json())
from sklearn.linear_model import LogisticRegression